---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator-ceph
  namespace: kube-monitor
  labels:
    app: ceph
spec:
  externalName: 10.0.0.51
  type: ExternalName
  ports:
  - name: metrcis
    port: 9283
    targetPort: 9283
    protocol: TCP
  type: ClusterIP
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: prometheus-operator-ceph
  namespace: kube-monitor
  labels:
    app: ceph
subsets:
  - addresses:
    - ip: 10.0.0.51
      nodeName: ceph
    ports:
    - name: metrcis
      port: 9283
      protocol: TCP
