apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
imageRepository: 172.18.0.4:5000
kubernetesVersion: v1.13.3
controlPlaneEndpoint: 172.18.0.2:6443
apiServer:
  certSANs:
    - 172.18.0.2
networking:
  serviceSubnet: 10.96.0.0/12
  podSubnet: 10.244.0.0/16
