apiVersion: v1
kind: Service
metadata:
  name: postgres-database
  namespace: kube-database
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 35432
  type: NodePort
  selector:
    app: postgres

