name: e2e

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  kind:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        provider:
          - istio
          - linkerd
          - contour
          - nginx
          - traefik
          - gloo
          - skipper
          - osm
          - kubernetes
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Kubernetes
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.0"
          image: kindest/node:v1.21.1@sha256:fae9a58f17f18f06aeac9772ca8b5ac680ebbed985e266f711d936e91d113bad
      - name: Build container image
        run: |
          docker build -t test/flagger:latest .
          kind load docker-image test/flagger:latest
      - name: Run tests
        run: |
          ./test/${{ matrix['provider'] }}/run.sh
