apiVersion: v1
kind: Pod
metadata:
  annotations:
  labels:
    app: ceph-exporter
    pod-template-generation: "1"
  name: ceph-exporter
  namespace: kube-ceph
spec:
  containers:
  - image: digitalocean/ceph_exporter:2.0.6-luminous
    imagePullPolicy: IfNotPresent
    name: ceph-exporter
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 200Mi
    volumeMounts:
    - mountPath: /etc/ceph
      name: ceph-conf
  hostNetwork: true
  nodeName: 10.0.0.51   #Ceph宿主机的ip
  nodeSelector:
    kubernetes.io/hostname: 10.0.0.51  #Ceph宿主机的ip
  restartPolicy: Always
  serviceAccount: default
  serviceAccountName: default
  volumes:
  - hostPath:
      path: /etc/ceph
    name: ceph-conf
