---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: ceph-exporter
    k8s-app: ceph-exporter
  name: ceph-exporter
  namespace: kube-monitor
spec:
  ports:
  - name: ceph-exporter
    port: 9128
    protocol: TCP
    targetPort: 9128
  selector:
    app: ceph-exporter


