---
apiVersion: v1
kind: Service
metadata:
  name: oracle-database
  namespace: kube-database
spec:
  selector:
    app: oracle-database
    version: 12.1.0.1
  ports:
  - protocol: TCP
    port: 1521
    targetPort: 1521
    nodePort: 31521
  type: NodePort
    

