{{- if and .Values.configMap.create (empty .Values.configMap.existingConfigMap) -}}
{{- if empty .Values.configMap.config -}}
  {{- fail "Missing config from \".Values.configMap.config\"!" -}}
{{- end -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" (include "gitlab.fullname" .) }}
  labels:
    {{- include "gitlab.labels" . | nindent 4 }}
    {{- with .Values.configMap.labels }}
    {{ toYaml . | indent 4 }}
    {{- end }}
  {{- with .Values.configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{ default "gitlab.rb" .Values.configMap.key }}: |
    {{- .Values.configMap.config | nindent 4 }}

    {{- if and .Values.healthCheck.enabled .Values.healthCheck.whitelist }}
    # ensure kubelet probes are whitelisted
    gitlab_rails['monitoring_whitelist'] = [
      {{- range $i, $val := .Values.healthCheck.whitelist }}
      {{ $val | squote }},
      {{- end }}
    ]
    {{- end }}
{{- end }}
