{{- if .Values.deployment.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gitlab.fullname" . }}
  labels:
    {{- include "gitlab.labels" . | nindent 4 }}
    {{- with .Values.deployment.labels }}
    {{ toYaml . | indent 4 }}
    {{- end }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.deployment.replicas }}
  replicas: {{ .Values.deployment.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gitlab.selectorLabels" . | nindent 6 }}
  {{- with .Values.deployment.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.deployment.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gitlab.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "gitlab.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range $key, $val := .Values.ports }}
            {{- if $val.enabled }}
            - name: {{ $key | quote }}
              containerPort: {{ $val.port }}
              protocol: {{ default "TCP" $val.protocol | quote }}
            {{- end }}
            {{- end }}
          env:
            - name: GITLAB_OMNIBUS_CONFIG
              valueFrom:
                configMapKeyRef:
                {{- if .Values.configMap.existingConfigMap }}
                  name: {{ .Values.configMap.existingConfigMap }}
                {{- else }}
                  name: {{ printf "%s-config" (include "gitlab.fullname" . ) }}
                {{- end }}
                  key: {{ default "gitlab.rb" .Values.configMap.key }}
            {{- range $i, $val := .Values.env }}
            - name: {{ $val.name | quote }}
              value: {{ $val.value | quote }}
            {{- end }}
          volumeMounts:
            {{- range $i, $pvc := .Values.persistentVolumeClaims }}
            - name: {{ printf "%s-volume" ($pvc.name) }}
              mountPath: {{ $pvc.mountPath }}
            {{- end }}
            {{- if eq (include "gitlab.backups.enabled" . ) "true" }}
            - name: backups-volume
              mountPath: {{ include "gitlab.backups.mountPath" . }}
            {{- end }}
          {{- if .Values.healthCheck.enabled }}
          startupProbe:
            httpGet:
              path: /-/health
              port: http
            failureThreshold: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /-/liveness
              port: http
          readinessProbe:
            httpGet:
              path: /-/readiness
              port: http
          {{- end }}
          resources: {{ if not .Values.resources -}}{}{{- end }}
            {{- if .Values.resources }}
            {{- toYaml .Values.resources | nindent 12 }}
            {{- end }}
      volumes:
        {{- range $i, $pvc := .Values.persistentVolumeClaims }}
        - name: {{ printf "%s-volume" ($pvc.name) }}
          persistentVolumeClaim:
            {{- if and $pvc.create (empty $pvc.existingPersistentVolumeClaim) }}
            claimName: {{ printf "%s-%s" (include "gitlab.fullname" $ ) $pvc.name }}
            {{- else }}
            claimName: {{ $pvc.existingPersistentVolumeClaim }}
            {{- end }}
        {{- end }}
        {{- if eq (include "gitlab.backups.enabled" . ) "true" }}
        - name: backups-volume
          hostPath:
            type: Directory
            path: {{ include "gitlab.backups.hostPath" . }}
        {{- end }}
      {{- if .Values.securityContext }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      {{- end }}
{{- end }}
