apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

namespace: dingtalk

commonLabels:
  app: alertmanager-webhook-dingtalk


images:
  - name: timonwong/prometheus-webhook-dingtalk
    newTag: v2.0.0

configMapGenerator:
  - name: alertmanager-webhook-dingtalk
    files:
      - config/config.yaml
      - config/template.tmpl
