apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostnames-deployment
spec:
  selector:
    matchLabels:
      app: hostnames
  replicas: 3
  template:
    metadata:
      labels:
        app: hostnames
    spec:
      containers:
      - name: hostnames
        image: k8s.gcr.io/serve_hostname:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9376
        #volumeMounts:
        #- mountPath: "/usr/share/nginx/html"
        #  name: nginx-vol
      #volumes:
      #- name: nginx-vol
      #  emptyDir: {}
