#grep key /etc/ceph/ceph.client.admin.keyring | awk '{printf "%s",$NF}'| base64

apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret-admin
  namespace: cephfs
type: "kubernetes.io/rbd"
data:
  # ceph auth get-key client.admin | base64
  key: QVFBYTdZMWNvMGlDS2hBQUZXcWJhS1l1Z1BiMGl1WnQvSnBXOWc9PQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
  namespace: cephfs
type: "kubernetes.io/rbd"
data:
  # ceph auth add client.kube mon 'allow r' osd 'allow rwx pool=kube'
  # ceph auth get-key client.kube | base64
  key: QVFDdkpaTmM0UmZWSVJBQXBsL25OL3E2VnZyelBsaWttQUZna2c9PQ==
