kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cephfs
  namespace : cephfs
provisioner: ceph.com/cephfs
parameters:
    monitors: 10.0.0.51:6789,10.0.0.52:6789,10.0.0.53:6789
    adminId: admin
    adminSecretName: ceph-secret-admin
    adminSecretNamespace: "cephfs"
    claimRoot: /pvc-volumes

