apiVersion: v1
kind: Pod
metadata:
  name: cephfs-pod-nginx
  namespace: cephfs
spec:
  containers:
  - name: cephfs-nginx
    image: nginx:1.7.9          
    volumeMounts:
    - name: cephfs       
      mountPath: /usr/local/share/nginx/html
      readOnly: false
  restartPolicy: "Never"
  volumes:
  - name: cephfs         
    persistentVolumeClaim:
      claimName: cephfs-pvc
