# Source: gitlab/templates/persistentvolumeclaim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-gitlab-secrets
  labels:
    helm.sh/chart: gitlab-0.2.5
    app.kubernetes.io/name: gitlab
    app.kubernetes.io/instance: git
    app.kubernetes.io/version: "14.9.2-ce.0"
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
  volumeMode: Filesystem
  storageClassName: local-path

