# Source: gitlab/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: git-gitlab
  labels:
    helm.sh/chart: gitlab-0.2.5
    app.kubernetes.io/name: gitlab
    app.kubernetes.io/instance: git
    app.kubernetes.io/version: "14.9.2-ce.0"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: git-gitlab
subjects:
  - kind: ServiceAccount
    name: default
    namespace: longhorn-system

