apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
    chart: prometheus-9.7.2
    component: alertmanager
    heritage: Tiller
    release: prometheus
  name: prometheus-alertmanager-nodeport
  namespace: kube-monitor
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9093
    nodePort: 39093
  selector:
    app: prometheus
    component: alertmanager
    release: prometheus
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
