#ceph auth get client.admin 2>&1 |grep "key = " |awk '{print  $3'} |xargs echo -n > /tmp/key
## userKey from /tmp/key
---
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: default
stringData:
  # Required for statically provisioned volumes
  userID: kube
  userKey: AQAZ4d9dT0weORAAAdeqKDLAEf8GAtr6LL0WPQ==

  # Required for dynamically provisioned volumes
  adminID: admin
  adminKey: AQCNxt9dutANNhAArG7ctqcE+tmn/GMGTHkkww==
