apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: kube-database
  labels:
    app: mysql-database
spec:
  storageClassName: fast-rbd
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
