apiVersion: v1
kind: Service
metadata:
  name: mysql-database
  namespace: kube-database
  labels:
    app: mysql-database
spec:
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 33306
  selector:
    app: mysql-database
  type: NodePort
