# Source: gitlab/charts/certmanager/templates/cainjector-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab-certmanager-cainjector
  labels:
    app: cainjector
    app.kubernetes.io/name: cainjector
    app.kubernetes.io/instance: gitlab
    app.kubernetes.io/component: "cainjector"
    app.kubernetes.io/version: "v1.5.4"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: certmanager-v1.5.4
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitlab-certmanager-cainjector
subjects:
  - name: gitlab-certmanager-cainjector
    namespace: "redis"
    kind: ServiceAccount

