# Source: gitlab/charts/certmanager/templates/webhook-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab-certmanager-webhook:subjectaccessreviews
  labels:
    app: webhook
    app.kubernetes.io/name: webhook
    app.kubernetes.io/instance: gitlab
    app.kubernetes.io/component: "webhook"
    app.kubernetes.io/version: "v1.5.4"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: certmanager-v1.5.4
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitlab-certmanager-webhook:subjectaccessreviews
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: gitlab-certmanager-webhook
  namespace: redis

