# Source: gitlab/charts/prometheus/templates/server/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    component: "server"
    app: prometheus
    release: gitlab
    chart: prometheus-15.0.4
    heritage: Helm
  name: gitlab-prometheus-server
subjects:
  - kind: ServiceAccount
    name: gitlab-prometheus-server
    namespace: redis
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitlab-prometheus-server

