# Source: gitlab/charts/nginx-ingress/templates/controller-configmap-addheaders.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: nginx-ingress
    chart: nginx-ingress-4.0.6
    release: gitlab
    heritage: Helm
    
    component: "controller"
    helm.sh/chart: nginx-ingress-4.0.6
    app.kubernetes.io/version: "1.0.4"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: gitlab-nginx-ingress-custom-add-headers
  namespace: redis
data: 
  Referrer-Policy: strict-origin-when-cross-origin

