# Source: gitlab/charts/nginx-ingress/templates/controller-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: nginx-ingress
    chart: nginx-ingress-4.0.6
    release: gitlab
    heritage: Helm
    
    component: "controller"
    helm.sh/chart: nginx-ingress-4.0.6
    app.kubernetes.io/version: "1.0.4"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: gitlab-nginx-ingress-controller
  namespace: redis
data:
  allow-snippet-annotations: "true"
  add-headers: redis/gitlab-nginx-ingress-custom-add-headers
    
  hsts: "true"
    
  hsts-include-subdomains: "false"
    
  hsts-max-age: "63072000"
    
  server-name-hash-bucket-size: "256"
    
  server-tokens: "false"
    
  ssl-ciphers: "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4"
    
  ssl-protocols: "TLSv1.3 TLSv1.2"
    
  use-http2: "true"

