# Source: gitlab/charts/certmanager/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-certmanager
  namespace: "redis"
  labels:
    app: certmanager
    app.kubernetes.io/name: certmanager
    app.kubernetes.io/instance: gitlab
    app.kubernetes.io/component: "controller"
    app.kubernetes.io/version: "v1.5.4"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: certmanager-v1.5.4
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: certmanager
      app.kubernetes.io/instance: gitlab
      app.kubernetes.io/component: "controller"
  template:
    metadata:
      labels:
        app: certmanager
        app.kubernetes.io/name: certmanager
        app.kubernetes.io/instance: gitlab
        app.kubernetes.io/component: "controller"
        app.kubernetes.io/version: "v1.5.4"
        app.kubernetes.io/managed-by: Helm
        helm.sh/chart: certmanager-v1.5.4
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9402'
    spec:
      serviceAccountName: gitlab-certmanager
      securityContext:
        runAsNonRoot: true
      containers:
        - name: certmanager
          image: "quay.io/jetstack/cert-manager-controller:v1.5.4"
          imagePullPolicy: IfNotPresent
          args:
          - --v=2
          - --cluster-resource-namespace=$(POD_NAMESPACE)
          - --leader-election-namespace=kube-system
          ports:
          - containerPort: 9402
            protocol: TCP
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          resources:
            {}

