# Source: gitlab/charts/certmanager/templates/cainjector-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-certmanager-cainjector
  namespace: "redis"
  labels:
    app: cainjector
    app.kubernetes.io/name: cainjector
    app.kubernetes.io/instance: gitlab
    app.kubernetes.io/component: "cainjector"
    app.kubernetes.io/version: "v1.5.4"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: certmanager-v1.5.4
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cainjector
      app.kubernetes.io/instance: gitlab
      app.kubernetes.io/component: "cainjector"
  template:
    metadata:
      labels:
        app: cainjector
        app.kubernetes.io/name: cainjector
        app.kubernetes.io/instance: gitlab
        app.kubernetes.io/component: "cainjector"
        app.kubernetes.io/version: "v1.5.4"
        app.kubernetes.io/managed-by: Helm
        helm.sh/chart: certmanager-v1.5.4
    spec:
      serviceAccountName: gitlab-certmanager-cainjector
      securityContext:
        runAsNonRoot: true
      containers:
        - name: certmanager
          image: "quay.io/jetstack/cert-manager-cainjector:v1.5.4"
          imagePullPolicy: IfNotPresent
          args:
          - --v=2
          - --leader-election-namespace=kube-system
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          resources:
            {}

