# Source: gitlab/charts/certmanager/templates/startupapicheck-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: gitlab-certmanager-startupapicheck
  namespace: "redis"
  labels:
    app: startupapicheck
    app.kubernetes.io/name: startupapicheck
    app.kubernetes.io/instance: gitlab
    app.kubernetes.io/component: "startupapicheck"
    app.kubernetes.io/version: "v1.5.4"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: certmanager-v1.5.4
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "1"
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: startupapicheck
        app.kubernetes.io/name: startupapicheck
        app.kubernetes.io/instance: gitlab
        app.kubernetes.io/component: "startupapicheck"
        app.kubernetes.io/version: "v1.5.4"
        app.kubernetes.io/managed-by: Helm
        helm.sh/chart: certmanager-v1.5.4
    spec:
      restartPolicy: OnFailure
      serviceAccountName: gitlab-certmanager-startupapicheck
      securityContext:
        runAsNonRoot: true
      containers:
        - name: certmanager
          image: "quay.io/jetstack/cert-manager-ctl:v1.5.4"
          imagePullPolicy: IfNotPresent
          args:
          - check
          - api
          - --wait=1m
          resources:
            {}

