# Source: gitlab/charts/registry/templates/pdb.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: gitlab-registry-v1
  namespace: redis
  labels:
    app: registry
    chart: registry-0.7.0
    release: gitlab
    heritage: Helm
    
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: registry
      release: gitlab

