# Source: gitlab/charts/gitlab/charts/gitaly/templates/pdb.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: gitlab-gitaly
  namespace: redis
  labels:
    app: gitaly
    chart: gitaly-5.9.2
    release: gitlab
    heritage: Helm
    
spec:
  maxUnavailable:  1
  selector:
    matchLabels:
      app: gitaly
      release: gitlab

