# Source: gitlab/charts/gitlab-runner/templates/role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: "RoleBinding"
metadata:
  name: gitlab-gitlab-runner
  labels:
    app: gitlab-gitlab-runner
    chart: gitlab-runner-0.39.0
    release: "gitlab"
    heritage: "Helm"
  namespace: "redis"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: "Role"
  name: gitlab-gitlab-runner
subjects:
- kind: ServiceAccount
  name: gitlab-gitlab-runner
  namespace: "redis"

