# Source: gitlab/charts/certmanager/templates/webhook-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-certmanager-webhook:dynamic-serving
  namespace: "redis"
  labels:
    app: webhook
    app.kubernetes.io/name: webhook
    app.kubernetes.io/instance: gitlab
    app.kubernetes.io/component: "webhook"
    app.kubernetes.io/version: "v1.5.4"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: certmanager-v1.5.4
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitlab-certmanager-webhook:dynamic-serving
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: gitlab-certmanager-webhook
  namespace: redis

