# Source: gitlab/charts/nginx-ingress/templates/controller-service-metrics.yaml
apiVersion: v1
kind: Service
metadata:
  annotations: 
    gitlab.com/prometheus_port: "10254"
    gitlab.com/prometheus_scrape: "true"
    prometheus.io/port: "10254"
    prometheus.io/scrape: "true"
  labels:
    app: nginx-ingress
    chart: nginx-ingress-4.0.6
    release: gitlab
    heritage: Helm
    
    component: "controller"
    helm.sh/chart: nginx-ingress-4.0.6
    app.kubernetes.io/version: "1.0.4"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: gitlab-nginx-ingress-controller-metrics
  namespace: redis
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 10254
      protocol: TCP
      targetPort: metrics
  selector:
    app: nginx-ingress
    release: gitlab
    component: "controller"

