# Source: gitlab/charts/prometheus/templates/server/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: "server"
    app: prometheus
    release: gitlab
    chart: prometheus-15.0.4
    heritage: Helm
  name: gitlab-prometheus-server
  namespace: redis
  annotations:
    {}

