# Source: gitlab/charts/prometheus/templates/server/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    component: "server"
    app: prometheus
    release: gitlab
    chart: prometheus-15.0.4
    heritage: Helm
  name: gitlab-prometheus-server
  namespace: redis
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9090
  selector:
    component: "server"
    app: prometheus
    release: gitlab
  sessionAffinity: None
  type: "ClusterIP"

