apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-metallb
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.0.0.60-10.0.0.80

