apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.10.6.240-10.10.6.250
    node-selectors:
    - match-labels:
        vlan: vlan6
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.10.7.240-10.10.6.250
    node-selectors:
    - match-labels:
        vlan: vlan7
#kubectl label nodes <node-name> vlan=vlan7
#kubectl label nodes <node-name> vlan=vlan6
